apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kilo-financial-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kilo-financial
  namespaceSelector:
    matchNames:
      - kilo-guardian
  endpoints:
    - port: http
      path: /metrics
      honorLabels: true
