apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: kilo-guardian
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kilo-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-brain-pdb
  namespace: kilo-guardian
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kilo-ai-brain
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: kilo-guardian
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kilo-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-brain-hpa
  namespace: kilo-guardian
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kilo-ai-brain
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
